spring :
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://129.154.50.169:5432/tentalk
    username: tentalk
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver